<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<!-- ====================================================================== -->
	<!-- PARENT                                                                 -->
	<!-- ====================================================================== -->
	<parent>
		<groupId>dena.api.common</groupId>
		<artifactId>denaCommonInteropAPI</artifactId>
		<version>${revision}</version>
	</parent>


	<!-- ====================================================================== -->
	<!-- ARTIFACT                                                               -->
	<!-- ====================================================================== -->
	<name>denaCommonInteropAPIModelClasses</name>
	<artifactId>denaCommonInteropAPIModelClasses</artifactId>
	<packaging>jar</packaging>

	<!-- ====================================================================== -->
	<!-- DEPENDENCIES                                                           -->
	<!-- ====================================================================== -->
	<dependencies>		
		<!-- ///////////////////////////////////////// -->
		<!--  DENA: Common Model                       -->
		<!-- ///////////////////////////////////////// -->		
		<dependency>
			<groupId>dena.api.common</groupId>
			<artifactId>denaCommonAPIModelClasses</artifactId>
			<version>${dena.api.common.version}</version>
		</dependency>
	</dependencies>
</project>